apiVersion: "tinkerbell.org/v1alpha1"
kind: Template
metadata:
  name: wipe-disks
  namespace: tink-system
spec:
  data: |
    version: "0.1"
    name: wipe_disks
    global_timeout: 1800
    tasks:
      - name: "os-installation"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
        actions:
          - name: "disk-wipe"
            image: docker.io/irishgordo/wipe-disk:latest
            timeout: 600
