//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleLocation) DeepCopyInto(out *CattleLocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleLocation.
func (in *CattleLocation) DeepCopy() *CattleLocation {
	if in == nil {
		return nil
	}
	out := new(CattleLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CattleLocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleLocationList) DeepCopyInto(out *CattleLocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CattleLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleLocationList.
func (in *CattleLocationList) DeepCopy() *CattleLocationList {
	if in == nil {
		return nil
	}
	out := new(CattleLocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CattleLocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleLocationSpec) DeepCopyInto(out *CattleLocationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleLocationSpec.
func (in *CattleLocationSpec) DeepCopy() *CattleLocationSpec {
	if in == nil {
		return nil
	}
	out := new(CattleLocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleLocationStatus) DeepCopyInto(out *CattleLocationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleLocationStatus.
func (in *CattleLocationStatus) DeepCopy() *CattleLocationStatus {
	if in == nil {
		return nil
	}
	out := new(CattleLocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkLoadout) DeepCopyInto(out *CattleNetworkLoadout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkLoadout.
func (in *CattleNetworkLoadout) DeepCopy() *CattleNetworkLoadout {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkLoadout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CattleNetworkLoadout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkLoadoutList) DeepCopyInto(out *CattleNetworkLoadoutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CattleNetworkLoadout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkLoadoutList.
func (in *CattleNetworkLoadoutList) DeepCopy() *CattleNetworkLoadoutList {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkLoadoutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CattleNetworkLoadoutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkLoadoutSpec) DeepCopyInto(out *CattleNetworkLoadoutSpec) {
	*out = *in
	out.Unifi = in.Unifi
	in.UnifiResults.DeepCopyInto(&out.UnifiResults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkLoadoutSpec.
func (in *CattleNetworkLoadoutSpec) DeepCopy() *CattleNetworkLoadoutSpec {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkLoadoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkLoadoutStatus) DeepCopyInto(out *CattleNetworkLoadoutStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkLoadoutStatus.
func (in *CattleNetworkLoadoutStatus) DeepCopy() *CattleNetworkLoadoutStatus {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkLoadoutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiClientWrapper) DeepCopyInto(out *CattleNetworkUnifiClientWrapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiClientWrapper.
func (in *CattleNetworkUnifiClientWrapper) DeepCopy() *CattleNetworkUnifiClientWrapper {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiClientWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiFlexBool) DeepCopyInto(out *CattleNetworkUnifiFlexBool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiFlexBool.
func (in *CattleNetworkUnifiFlexBool) DeepCopy() *CattleNetworkUnifiFlexBool {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiFlexBool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiFlexInt) DeepCopyInto(out *CattleNetworkUnifiFlexInt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiFlexInt.
func (in *CattleNetworkUnifiFlexInt) DeepCopy() *CattleNetworkUnifiFlexInt {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiFlexInt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiInfo) DeepCopyInto(out *CattleNetworkUnifiInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiInfo.
func (in *CattleNetworkUnifiInfo) DeepCopy() *CattleNetworkUnifiInfo {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiNetworkWrapper) DeepCopyInto(out *CattleNetworkUnifiNetworkWrapper) {
	*out = *in
	out.DhcpGuardEnabled = in.DhcpGuardEnabled
	out.DhcpRelayEnabled = in.DhcpRelayEnabled
	out.DhcpdDNSEnabled = in.DhcpdDNSEnabled
	out.DhcpdEnabled = in.DhcpdEnabled
	out.DhcpdGatewayEnabled = in.DhcpdGatewayEnabled
	out.DhcpdLeasetime = in.DhcpdLeasetime
	out.DhcpdTimeOffsetEnabled = in.DhcpdTimeOffsetEnabled
	out.Enabled = in.Enabled
	out.IsNat = in.IsNat
	out.Vlan = in.Vlan
	out.VlanEnabled = in.VlanEnabled
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiNetworkWrapper.
func (in *CattleNetworkUnifiNetworkWrapper) DeepCopy() *CattleNetworkUnifiNetworkWrapper {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiNetworkWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiResults) DeepCopyInto(out *CattleNetworkUnifiResults) {
	*out = *in
	if in.USWS != nil {
		in, out := &in.USWS, &out.USWS
		*out = make([]CattleNetworkUnifiUSWWrapper, len(*in))
		copy(*out, *in)
	}
	if in.UnifiNetworks != nil {
		in, out := &in.UnifiNetworks, &out.UnifiNetworks
		*out = make([]CattleNetworkUnifiNetworkWrapper, len(*in))
		copy(*out, *in)
	}
	if in.USGS != nil {
		in, out := &in.USGS, &out.USGS
		*out = make([]CattleNetworkUnifiUSGWrapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UDMS != nil {
		in, out := &in.UDMS, &out.UDMS
		*out = make([]CattleNetworkUnifiUDMWrapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]CattleNetworkUnifiClientWrapper, len(*in))
		copy(*out, *in)
	}
	if in.Sites != nil {
		in, out := &in.Sites, &out.Sites
		*out = make([]CattleNetworkUnifiSite, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiResults.
func (in *CattleNetworkUnifiResults) DeepCopy() *CattleNetworkUnifiResults {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiSite) DeepCopyInto(out *CattleNetworkUnifiSite) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiSite.
func (in *CattleNetworkUnifiSite) DeepCopy() *CattleNetworkUnifiSite {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiUDMWrapper) DeepCopyInto(out *CattleNetworkUnifiUDMWrapper) {
	*out = *in
	if in.DownlinkTable != nil {
		in, out := &in.DownlinkTable, &out.DownlinkTable
		*out = make([]CattleUnifiDownlinkTable, len(*in))
		copy(*out, *in)
	}
	if in.Temperatures != nil {
		in, out := &in.Temperatures, &out.Temperatures
		*out = make([]CattleUnifiTemperature, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiUDMWrapper.
func (in *CattleNetworkUnifiUDMWrapper) DeepCopy() *CattleNetworkUnifiUDMWrapper {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiUDMWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiUSGWrapper) DeepCopyInto(out *CattleNetworkUnifiUSGWrapper) {
	*out = *in
	if in.Temperatures != nil {
		in, out := &in.Temperatures, &out.Temperatures
		*out = make([]CattleUnifiTemperature, len(*in))
		copy(*out, *in)
	}
	in.Wan1.DeepCopyInto(&out.Wan1)
	in.Wan2.DeepCopyInto(&out.Wan2)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiUSGWrapper.
func (in *CattleNetworkUnifiUSGWrapper) DeepCopy() *CattleNetworkUnifiUSGWrapper {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiUSGWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiUSWWrapper) DeepCopyInto(out *CattleNetworkUnifiUSWWrapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiUSWWrapper.
func (in *CattleNetworkUnifiUSWWrapper) DeepCopy() *CattleNetworkUnifiUSWWrapper {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiUSWWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleNetworkUnifiWanWrapper) DeepCopyInto(out *CattleNetworkUnifiWanWrapper) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleNetworkUnifiWanWrapper.
func (in *CattleNetworkUnifiWanWrapper) DeepCopy() *CattleNetworkUnifiWanWrapper {
	if in == nil {
		return nil
	}
	out := new(CattleNetworkUnifiWanWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleUnifiDownlinkTable) DeepCopyInto(out *CattleUnifiDownlinkTable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleUnifiDownlinkTable.
func (in *CattleUnifiDownlinkTable) DeepCopy() *CattleUnifiDownlinkTable {
	if in == nil {
		return nil
	}
	out := new(CattleUnifiDownlinkTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CattleUnifiTemperature) DeepCopyInto(out *CattleUnifiTemperature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CattleUnifiTemperature.
func (in *CattleUnifiTemperature) DeepCopy() *CattleUnifiTemperature {
	if in == nil {
		return nil
	}
	out := new(CattleUnifiTemperature)
	in.DeepCopyInto(out)
	return out
}
