# permissions for end users to view cattlelocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cattlelocation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cattledogs-backend
    app.kubernetes.io/part-of: cattledogs-backend
    app.kubernetes.io/managed-by: kustomize
  name: cattlelocation-viewer-role
rules:
- apiGroups:
  - cattledogs.cattledogs-backend.gordoughnet.com
  resources:
  - cattlelocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cattledogs.cattledogs-backend.gordoughnet.com
  resources:
  - cattlelocations/status
  verbs:
  - get
