---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cattledogs.cattledogs-backend.gordoughnet.com
  resources:
  - cattlelocations
  - cattlenetworkloadouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cattledogs.cattledogs-backend.gordoughnet.com
  resources:
  - cattlelocations/finalizers
  - cattlenetworkloadouts/finalizers
  verbs:
  - update
- apiGroups:
  - cattledogs.cattledogs-backend.gordoughnet.com
  resources:
  - cattlelocations/status
  - cattlenetworkloadouts/status
  verbs:
  - get
  - patch
  - update
